name: Zizmor analysis

on:
  workflow_call:
    inputs:
      min_severity:
        description: "Minimum severity: informational|low|medium|high"
        required: false
        default: medium
        type: string
      min_confidence:
        description: "Minimum confidence: low|medium|high"
        required: false
        default: low
        type: string
      persona:
        description: "Audit persona: regular|pedantic|auditor"
        required: false
        default: regular
        type: string

jobs:
  zizmor:
    name: Security Scan
    if: ${{ (github.event_name != 'pull_request') || (github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Zizmor Config
        uses: MiraGeoscience/CI-tools/.github/actions/setup-zizmor-config@v2

      - name: Run Zizmor Security Scan
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4
        with:
          advanced-security: false
          annotations: false
          persona: ${{ inputs.persona }}
          min-severity: ${{ inputs.min_severity }}
          min-confidence: ${{ inputs.min_confidence }}
